dependencies {
  // openflexo dep
  implementation flexoFoundation()
  implementation flexoOntology()
  // external dep
  implementation group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.8.1"
  implementation group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.8.1"

  // testing dep
  testImplementation testUtils()
  testImplementation flexoFoundationTest()

  // A particular resource center can be defined here
  // If it always required to be present at run-time
  //runtimeOnly project(':xx-ta-rc')

  // Test resource center, if required
  // testRuntimeOnly project(':xx-ta-test-rc')

}

