dependencies {
    implementation project(':json-ta')
    implementation flexoFoundation()

    implementation testUtils()
    implementation flexoFoundationTest()

    implementation group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.8.1"
    implementation group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.8.1"
	// testing dep
    testImplementation flexoFoundation()
    testImplementation flexoFoundationTest()
    testImplementation fmlCli()
    testImplementation fmlCliTest()

    // Test resource center
    testRuntimeOnly project(':json-ta-test-rc')
}
