dependencies {
    implementation project(':json-ta')
    implementation flexoFoundation()

    implementation testUtils()
    implementation flexoFoundationTest()

	// testing dep
    testImplementation flexoFoundation()
    testImplementation flexoFoundationTest()
    testImplementation fmlCli()
    testImplementation fmlCliTest()

    // Test resource center
    testRuntimeOnly project(':json-ta-test-rc')
}
